import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/component/Navbar";
import  {BlogContextProvider}  from "@/context/BlogContextProvider";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
       <body className="bg-[#a0f1bd] ">
        <Navbar />
        <BlogContextProvider>{children}</BlogContextProvider>
      </body>
    </html>
  );
}
